import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dimensions.columns = 150
dimensions.lines = 85
decorations = "buttonless"
opacity = 0.95
blur = true

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18
