# import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
import = ["~/.config/alacritty/themes/themes/rose-pine-moon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6
dimensions.columns = 150
dimensions.lines = 85
decorations = "buttonless"
opacity = 1
blur = false

option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 18
